### ISSUE TITLE
프로젝트 구성에 대한 문의입니다.

### ISSUE THREAD

**Issue by Danue1** [chinsun9/draw-lots#1]
살펴 보던 중 몇몇 궁금한 부분이 있어 이슈를 만들어 문의해 봅니다.

1. [@emotion/react](https://www.npmjs.com/package/@emotion/react)를 사용하지 않고 [@emotion/css](https://emotion.sh/docs/@emotion/css)만으로 작성한 이유를 알고 싶습니다.

1. (아래와 링크한 부분처럼)해당 컴포넌트 바깥에서는 쓰이지 않는 CSS를 export 하는 것은 코딩 컨벤션일까요?
   https://github.com/chinsun9/draw-lots/blob/a38523b0b42034c86062424d63fbe351c0139be3/src/NextButton.tsx#L58-L63

1. components/ 디렉토리가 있지만 `<NextButton>`, `<Result>` 컴포넌트는 components/ 디렉토리 밖에 위치하더라구요.
   다른 의미가 있어서 그런 것일까요?

1. shuffle 함수는 [라이브러리](https://github.com/sindresorhus/array-shuffle)로 불러다 쓸 수 있는데 직접 내부 코드로 가져온 것은 [fisher-yates 알고리즘](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle)에 추가적인 개선을 해보려는 것이었을까요?
   https://github.com/chinsun9/draw-lots/blob/a38523b0b42034c86062424d63fbe351c0139be3/src/utils/index.ts#L1-L11

1. getRandomInt 보다는 [randRange](https://grep.app/search?q=randRange%28)(혹은 [randomRange](https://grep.app/search?q=randomRange%28))를 제안해 봅니다.
   getRandomInt라고 하면 get으로 시작해서 어떤 자료구조/객체의 메서드인 것 같은 느낌이더라구요. 표현하자면... Random.getRandomInt 처럼 써야 할 것 같은 느낌?
   https://github.com/chinsun9/draw-lots/blob/a38523b0b42034c86062424d63fbe351c0139be3/src/utils/index.ts#L13-L14

감사합니당!

**Comment by chinsun9** [comment]
오우 안녕하세요..!

1. emotion/react의 css를 사용했는데요. css prop으로 스타일을 주려고 했습니다. 지금 보니까 `@emotion/css`는 사용하지 않는데 받아놨군요..! 이거는 제거하도록 하겠습니다
2. 한 파일에서 작성하고 별도 파일로 추출하면서 생긴 실수입니다..! 
3. 2번이랑 동일하게 실수입니다..! 이거 만들때 새벽이고 벼락치기 하느라 정신이 없었습니다 ㅋㅋ 코드정리 한번 하겠습니다 👀 감사합니다!!
4. 오우 그런 의도는 전혀없었구요. 라이브러리를 사용하도록 변경하겠습니다!
5. 그렇군요. 저는 막 어색하거나 그러진 않는데요!! [mdn](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Math/random#%EB%91%90_%EA%B0%92_%EC%82%AC%EC%9D%B4%EC%9D%98_%EC%A0%95%EC%88%98_%EB%82%9C%EC%88%98_%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0) 에서 긁어왔습니다

정성스런 코멘트 감사합니다. 
이 이슈로 리팩토링 한번 하겠습니다!

**Comment by Danue1** [comment]
여러 문의와 제안을 받아 주셔서 감사합니다!
